Chore: Configure ESLint
tepeszCodes/document-management-system pull request #1
Opened 2021-08-14 17:21 UTC by tepeszCodes

#### What does this PR do?
Adds ESLint to our project

#### Description of Task to be completed?
Configure ESLint

#### How should this be manually tested?
run `npm run lint` in the project directory, if no errors occur, everything works fine.

2021-08-16 22:56 UTC, Avuidrauxs requested changes
Awesome job, just a few changes.

2021-08-16 22:56 UTC, Avuidrauxs commented on src/app.js
>  app.listen(process.env.port || 3000);
I will suggest you to do this ,

```suggestion
const PORT = process.env.port || 3000

app.get('/', (req, res) => {
  res.send('This is my first Express server');
});

app.listen(PORT, () => {
  console.log('Listening on port ' + PORT);
});
```

2021-08-17 08:02 UTC, tepeszCodes reviewed
@Avuidrauxs ok, I implemented suggested changes

2021-08-17 10:56 UTC, Avuidrauxs approved these changes
Looks good.

2021-08-17 10:57 UTC, merged