Multiple features and chores
tepeszCodes/document-management-system pull request #11
Opened 2021-11-06 14:58 UTC by tepeszCodes

#### What does this PR do?
It implements multiple chores and features (it is built on top of all other unmerged branches).
Implemented chores:
- Implement Swagger
- Add password hashing
Implemented features:
- Fetch all users
- Fetch all docs for given user
- Fetch all documents
- Search users by username, email or fullname
- Search documents by title
#### How should this be manually tested?
Test all endpoints specified in API documentation (after pulling this branch, run `npm run dev` and open localhost:3000/api-docs to access easy to read documentation. Endpoints cannot be tested directly from the documentation, as this would violate CORS rules. Documentation at this point is simply a good reference for manual testing with Postman
#### Any background context you want to provide?
This PR resolves almost all cards from the Trello board, the only card left in the icebox is setting roles
#### Questions:
How to properly secure the db from SQL injection? At the moment I'm passing all user queries directly to knex, should I validate each user input, and if so, how?

2021-11-11 21:14 UTC, Avuidrauxs requested changes
Looks great, just a few comments.

2021-11-11 21:14 UTC, Avuidrauxs commented on src/lib/bcrypt/index.js
> +/* eslint-disable require-jsdoc */
Let not be doing this in files, we can add rules for them

2021-11-11 21:14 UTC, Avuidrauxs commented on src/lib/bcrypt/index.js
> +  }
Lets have these as static methods:

```suggestion
  async static hashPwd(plainTextPassword) {
    return bcrypt.hash(plainTextPassword, 10);
  }

  async static comparePwd(plainTextPassword, hash) {
    return bcrypt.compare(plainTextPassword, hash);
  }
```

so we will use this as `Bcrypt.hashPwd('sdfs')`

2021-11-11 21:14 UTC, Avuidrauxs commented on src/lib/bcrypt/index.js
> +export default new Bcrypt();
Based on my previous comment, lets have this like below:

```suggestion
export default Bcrypt;
```

2021-11-12 14:28 UTC, tepeszCodes commented
@Avuidrauxs I implemented all suggested changes, PR ready for review

2021-11-18 15:33 UTC, Avuidrauxs approved these changes

2021-11-21 22:01 UTC, merged