Chore/integrate hound ci
tepeszCodes/document-management-system pull request #2
Opened 2021-08-14 17:46 UTC by tepeszCodes

### What does this PR do?
Adds Hound CI to our project

### How should this be manually tested?
There is no method to test it before merging. After merging with `main`, Hound will start commenting on new pull requests

### Screenshot
![screenshot hound ci](https://user-images.githubusercontent.com/54599709/129455892-cbe1dc9c-33ba-47c3-8fcb-bb8fc8a128a4.png)

2021-08-17 10:58 UTC, Avuidrauxs approved these changes

2021-08-17 10:59 UTC, Avuidrauxs requested changes
This looks like a it'll override lots of things from the first PR

2021-08-17 12:02 UTC, tepeszCodes commented
@Avuidrauxs I merged the main branch into this one, so now it should be ok

2021-08-18 19:45 UTC, Avuidrauxs approved these changes

2021-08-18 19:45 UTC, merged