Chore: Implement barrel pattern
tepeszCodes/document-management-system pull request #7
Opened 2021-08-20 12:49 UTC by tepeszCodes

#### What does this PR do?
Implements barrel pattern in our project
#### How should this be manually tested?
There is no other method than to look at the files and check if they are structured correctly and if imports / exports actually import / export what they should or not

2021-08-25 23:54 UTC, Avuidrauxs requested changes
Good job, just some small nitpicks and we're good to go.

2021-08-25 23:54 UTC, Avuidrauxs commented on src/lib/index.js
> +// eslint-disable-next-line import/prefer-default-export
### Nitpick

Disable this in the eslint file rather.

2021-08-25 23:54 UTC, Avuidrauxs commented on src/app.js
> +// const { errorHandlers } = middleware;
### Nitpick

Remove unused commented code

2021-08-25 23:54 UTC, Avuidrauxs commented on src/middleware/index.js
> +// eslint-disable-next-line import/prefer-default-export
### Nitpick

Lets disable it in the eslint config

2021-08-25 23:54 UTC, Avuidrauxs commented on src/middleware/logging/index.js
> +// eslint-disable-next-line import/prefer-default-export
### Nitpick

Lets disable it in the eslint config

2021-08-25 23:54 UTC, Avuidrauxs commented on src/middleware/errorHandlers/index.js
> +export default errorHandlers;
### Comment

This is a decent way of exporting also.

2021-08-26 09:27 UTC, saszaCodes commented
@Avuidrauxs ok, I implemented suggested changes

2021-08-26 13:16 UTC, Avuidrauxs approved these changes
LGTM!

2021-09-10 21:23 UTC, merged