Chore: Setup Knex.js
tepeszCodes/document-management-system pull request #8
Opened 2021-09-21 11:10 UTC by tepeszCodes

#### What does this PR do?
- sets up Knex.js, migration and seeding
- adds CRUD operations template class
- adds models for each table in database
- defines most of the routes defined in a [template document](https://docs.google.com/document/d/1cZqCmaFP--tI8nkjEOGY1x-Z-Wdn1oEUOsxeWACGlac/edit) and adds services handling conntections
#### Description of Task to be completed?
Setup Knex.js
#### How should this be manually tested?
To test if Knex.js is added properly and if migrations and seeding are set up, first run `npm run migrate:rollback`, this will drop all the tables in development db. Then, run `npm run migrate:latest` to add new tables and `npm run seed` to populate them. You can check if tables are created and populated correctly using RDBMS of your choice.

To test if routes, services and models are set up propetly, use Postman to test if each endpoint defined in `documentsRoute.js` and `usersRoute.js` behaves as expected. Server expects any data to be send in a JSON format and responds with data in the same format.
#### Any background context you want to provide?
I may have overinterpreted what I was supposed to do in this task. I was following the [template document](https://docs.google.com/document/d/1cZqCmaFP--tI8nkjEOGY1x-Z-Wdn1oEUOsxeWACGlac/edit) attached in the *Data should be persisted to a RDBMS storage* Trello card, but after adding all the models, services and routes I realized it was probably a template for the entire project, not just this one task. But what's done is done, I don't want to roll back so many commits that I have spent a lot of time on, so hopefully the way I implemented my solutions doesn't go against your plans for the next tasks.

Also, I implemented the tables in db a little bit differently - I moved `username` and `password` from `user_logins` to `user_profiles` table, as it seems to me to fall logically in the same category - general info about the user - whereas data stored in `user_logins` should, I think, contain only information about user logins, not their details.
#### Questions:
- Have I followed the barrel pattern correctly with all the new files?
- Are there any security concerns with storing all user details - username, email, password and fullname - in the one table?
- How should modules with classes be exported - should I instantiate a new object at the bottom of the file and export it (that's the way I did it in this PR), or export just the class and create new object in the files I import it to instead (this seems to violate the DRY rule, but maybe there are other reasons to do it this way)?

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/migrations/20210917093623_user_profiles.js
> +export function down(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/migrations/20210917093646_user_logins.js
> +export function down(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/migrations/20210917093623_user_profiles.js
> +export function up(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/migrations/20210917093653_documents.js
> +export function down(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/seeds/01_user_profiles.js
> +export function seed(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, tepeszCodes commented on src/lib/knex/seeds/02_user_logins.js
> +export function seed(knex) {
JSDoc left out intentionally

2021-09-21 11:13 UTC, saszaCodes commented on src/lib/knex/migrations/20210917093653_documents.js
> +export function up(knex) {
JSDoc left out intentionally

2021-09-21 11:14 UTC, tepeszCodes commented on src/lib/knex/migrations/20210917093646_user_logins.js
> +export function up(knex) {
JSDoc left out intentionally

2021-09-23 21:03 UTC, Avuidrauxs requested changes
Awesome job with the migration and seeding implementation

Just a few requested changes on how I want our classes implemented.

2021-09-23 21:03 UTC, Avuidrauxs commented on src/models/CRUD.js
> +export default class CRUD {
Here is the idea of how to implement an abstract class

```javascript
abstract class CrudOperations {
  public abstract create();

  public abstract update();

  public abstract delete();

  public abstract retrieve();
}

class Users extends CrudOperations {
  public create() {
    return null
  }
  
  public update() {
    return null
  }
  
  public delete() {
    return null
  }
  
  public retrieve() {
    return null
  }
}
```

2021-09-23 21:03 UTC, Avuidrauxs commented on src/models/documents.js
> +class Documents extends CRUD {
Will be nice to have a constructor where we initialize an instance of knex

```javascript
constructor(db) {
this.db = db; // Knex instance
}

async getAllDocuments () {

const documents = await this.db.select().from('documents').timeout(1000);
return documents
}
```

2021-09-23 21:03 UTC, Avuidrauxs commented on src/services/documentsService.js
> +export const documentsService = {
### Nitpick

- Make your services classes also

2021-09-23 21:03 UTC, Avuidrauxs commented on src/services/usersService.js
> +export const usersService = {
### Nitpick

- Make it a class

2021-10-21 11:51 UTC, saszaCodes commented
@Avuidrauxs ready for review. I only didn't create a constructor where knex is initialized, as this led to unexpected behavior, which I'd like to discuss today

2021-10-25 02:17 UTC, Avuidrauxs approved these changes
Looks great!

2021-10-25 21:01 UTC, merged